ref:
  T2T-CHM13v2.0: /scratch/ucgd/lustre-labs/vollger/assemblies/chm13v2.0.fa
  GRCh38: /scratch/ucgd/lustre-labs/vollger/assemblies/hg38.analysisSet.fa
tbl: config/HPRCv2.asm.tbl
aln_threads: 16
mm2_opts: "-x asm5 --secondary=no -s 25000 -K 8G"
second_aln: "no"
break_paf: 1000

